project_id = "xicdxswrtdassnlurnmp"

[functions.api]
verify_jwt = false

[functions.events]
verify_jwt = false

[functions.notifications]
verify_jwt = false

[functions.payments_webhook]
verify_jwt = false
